apiVersion: v1
kind: Service
metadata:
  name: credit-risk-api-service
  namespace: credit-risk
spec:
  type: ClusterIP
  selector:
    app: credit-risk-api
  ports:
    - port: 8000
      targetPort: 8000